### ISSUE TITLE
The solution for delete does not work

### ISSUE THREAD

**Issue by rogerprz** [learn-co-curriculum/crud-with-validations-lab#13]
The index delete portion is not valid. It redirects to the show page.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials so that the redirect returns to the songs index and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
