### ISSUE TITLE
"tbody > tr"

### ISSUE THREAD

**Issue by FreeBreadsticks** [learn-co-curriculum/crud-with-validations-lab#8]
Please put that the index page requires a table output to help people understand the errors!

**Comment by kwebster2** [comment]
@cernanb this is a good suggestion (regarding `spec/views/songs/index.html.erb_spec.rb:28)` This error often sends students on a wild goose chase for what is causing the error. I think we should either change how this is being tested so that it doesn't require a table, or specify in the README that a table is expected.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
